version: '3.8'

services:
  db:
    image: postgres:alpine3.20
    container_name: postgres_db
    environment:
      POSTGRES_USER: gca
      POSTGRES_PASSWORD: gca
      POSTGRES_DB: gym-crm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
